### PR TITLE
Webcore link updated

### LINKED ISSUE #99: (URGENT) "webcore" font location at opensuse.org now fails due to updated version and rename
```
Downloading font "webcore" from https://download.opensuse.org/repositories/home:/alteratio:/Common/openSUSE_13.2/src/webcore-fonts-3.0-2.1.src.rpm
2444
/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/fontist-1.11.1/lib/fontist/utils/downloader.rb:84:in `rescue in download_file': Invalid URL: https://download.opensuse.org/repositories/home:/alteratio:/Common/openSUSE_13.2/src/webcore-fonts-3.0-2.1.src.rpm (Fontist::Errors::InvalidResourceError)
2445
```

We need to do something with these constant version updates.

### PR DESCRIPTION
**Pull request by alemorozov**
Closes #99

### CODE REVIEW

**Comment by ronaldtse** [comment]
@alexeymorozov the problem is that the package was renamed from `openSUSE_13.2/src/webcore-fonts-3.0-2.1.src.rpm` to `openSUSE_13.2/src/webcore-fonts-vista-3.0-2.1.src.rpm`.

**Comment by ronaldtse** [comment]
Please merge anytime, thanks.

**Comment by alemorozov** [comment]
@ronaldtse Could not understand how it can be. It works properly for me without renaming:

```
$ curl -Lv https://download.opensuse.org/repositories/home:/alteratio:/Common/openSUSE_13.2/src/webcore-fonts-3.0-2.1.src.rpm

*   Trying 195.135.221.134...
* TCP_NODELAY set
* Connected to download.opensuse.org (195.135.221.134) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=opensuse.org
*  start date: Aug 30 00:24:01 2021 GMT
*  expire date: Nov 28 00:24:00 2021 GMT
*  subjectAltName: host "download.opensuse.org" matched cert's "*.opensuse.org"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f915400d600)
> GET /repositories/home:/alteratio:/Common/openSUSE_13.2/src/webcore-fonts-3.0-2.1.src.rpm HTTP/2
> Host: download.opensuse.org
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 302
< date: Mon, 30 Aug 2021 13:42:22 GMT
< server: Apache/2.4.43 (Linux/SUSE)
< location: https://mirrorcache.opensuse.org/repositories/home:/alteratio:/Common/openSUSE_13.2/src/webcore-fonts-3.0-2.1.src.rpm
< content-length: 393
< content-type: text/html; charset=iso-8859-1
<
* Ignoring the response-body
* Connection #0 to host download.opensuse.org left intact
* Issue another request to this URL: 'https://mirrorcache.opensuse.org/repositories/home:/alteratio:/Common/openSUSE_13.2/src/webcore-fonts-3.0-2.1.src.rpm'
*   Trying 195.135.221.140...
* TCP_NODELAY set
* Connected to mirrorcache.opensuse.org (195.135.221.140) port 443 (#1)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=opensuse.org
*  start date: Aug 30 00:25:16 2021 GMT
*  expire date: Nov 28 00:25:15 2021 GMT
*  subjectAltName: host "mirrorcache.opensuse.org" matched cert's "*.opensuse.org"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f915400d600)
> GET /repositories/home:/alteratio:/Common/openSUSE_13.2/src/webcore-fonts-3.0-2.1.src.rpm HTTP/2
> Host: mirrorcache.opensuse.org
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 302
< location: https://mirrorcache-eu.opensuse.org/repositories/home:/alteratio:/Common/openSUSE_13.2/src/webcore-fonts-3.0-2.1.src.rpm
< date: Mon, 30 Aug 2021 13:42:23 GMT
< content-length: 0
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< referrer-policy: no-referrer-when-downgrade
< strict-transport-security: max-age=15768000
<
* Connection #1 to host mirrorcache.opensuse.org left intact
* Issue another request to this URL: 'https://mirrorcache-eu.opensuse.org/repositories/home:/alteratio:/Common/openSUSE_13.2/src/webcore-fonts-3.0-2.1.src.rpm'
*   Trying 195.135.221.140...
* TCP_NODELAY set
* Connected to mirrorcache-eu.opensuse.org (195.135.221.140) port 443 (#2)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=opensuse.org
*  start date: Aug 30 00:25:16 2021 GMT
*  expire date: Nov 28 00:25:15 2021 GMT
*  subjectAltName: host "mirrorcache-eu.opensuse.org" matched cert's "*.opensuse.org"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f915400d600)
> GET /repositories/home:/alteratio:/Common/openSUSE_13.2/src/webcore-fonts-3.0-2.1.src.rpm HTTP/2
> Host: mirrorcache-eu.opensuse.org
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 302
< content-length: 0
< date: Mon, 30 Aug 2021 13:42:23 GMT
< location: https://ftp.gwdg.de/pub/opensuse/repositories/home:/alteratio:/Common/openSUSE_13.2/src/webcore-fonts-3.0-2.1.src.rpm
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< referrer-policy: no-referrer-when-downgrade
< strict-transport-security: max-age=15768000
<
* Connection #2 to host mirrorcache-eu.opensuse.org left intact
* Issue another request to this URL: 'https://ftp.gwdg.de/pub/opensuse/repositories/home:/alteratio:/Common/openSUSE_13.2/src/webcore-fonts-3.0-2.1.src.rpm'
*   Trying 134.76.12.6...
* TCP_NODELAY set
* Connected to ftp.gwdg.de (134.76.12.6) port 443 (#3)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=DE; ST=NIEDERSACHSEN; L=GOETTINGEN; O=Gesellschaft fuer wissenschaftliche Datenverarbeitung; CN=ftp6.gwdg.de
*  start date: May 20 07:41:32 2021 GMT
*  expire date: Jun 20 07:41:32 2022 GMT
*  subjectAltName: host "ftp.gwdg.de" matched cert's "ftp.gwdg.de"
*  issuer: C=DE; O=Verein zur Foerderung eines Deutschen Forschungsnetzes e. V.; OU=DFN-PKI; CN=DFN-Verein Global Issuing CA
*  SSL certificate verify ok.
> GET /pub/opensuse/repositories/home:/alteratio:/Common/openSUSE_13.2/src/webcore-fonts-3.0-2.1.src.rpm HTTP/1.1
> Host: ftp.gwdg.de
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx
< Date: Mon, 30 Aug 2021 13:42:24 GMT
< Content-Type: application/x-redhat-package-manager
< Content-Length: 7962466
< Last-Modified: Wed, 01 Jun 2016 01:06:15 GMT
< Connection: keep-alive
< ETag: "574e3507-797f62"
< Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
< X-Frame-Options: SAMEORIGIN
< X-Content-Type-Options: nosniff
< Accept-Ranges: bytes
<
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
* Failed writing body (0 != 15984)
* Closing connection 3
* TLSv1.2 (OUT), TLS alert, close notify (256):
* Closing connection 2
* Closing connection 0
* Closing connection 1
```

Do you have different output of this command? :(

**Comment by ronaldtse** [comment]
Strange! It was a failure in a GHA metanorma run. Or did it fail due to multiple 302 returns?

**Comment by alemorozov** [comment]
> Strange! It was a failure in a GHA metanorma run. Or did it fail due to multiple 302 returns?

I think it fails, but sometimes, occasionally, returning the 404 error.

**Pull request merged**
