### PR TITLE
Import google's formulas

### PR DESCRIPTION
**Pull request by CAMOBAP**
Because google CI is broken, an manual update

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP ! Feel free to merge when ready.

**Comment by ronaldtse** [comment]
We have a failure here:

```
test/test_formulas.rb:124:in `print_errors': There are errors occured. (RuntimeError)
	from test/test_formulas.rb:29:in `call'
	from test/test_formulas.rb:128:in `<main>'
google/noto_serif_hk, Invalid URL: https://fonts.google.com/download?family=Noto%20Serif%20HK. Error: #<Down::TimeoutError: timed out while reading data>.
```

**Comment by CAMOBAP** [comment]
> We have a failure

Actually, I increased them locally and forgot. I think makes sense to allow end users to configure it through some `~/.fontist/config.yml` our CLI, @ronaldtse make sense?

**Comment by ronaldtse** [comment]
@CAMOBAP agree with a config.yml for fontist. Could you help create that ticket?

**Comment by ronaldtse** [comment]
@alexeymorozov is reviewing this now. Thanks!

**Comment by ronaldtse** [comment]
@alexeymorozov is this still necessary? Thanks.

**Comment by alemorozov** [comment]
`fontist config` is done and all formulas are incorporated into the main branch now. By this cause closing.

**Pull request closed without merging**
