### PR TITLE
Cambria 5.24

### LINKED ISSUE #108: Update Cambria formula to use v5.24 from PCLinuxOS (was: Cambria from `PowerPointViewer.exe` does not support U+2009 "thin space")
As described in https://github.com/CalConnect/csd-transcription-systems/issues/94#issuecomment-937637492

Occasionally we see the `#` shown in rendering through Fontist installs of Cambria:
image

The reason is that the Cambria installed from PowerPointViewer.exe does not contain U+2009:
image

(font version is 1.02, 2016 vs. 5.97 2009 locally installed)

The normal Cambria installed via Office is of a newer version and contains the thin space.

Perhaps there is another openly installable Cambria that is a newer version with the thin space.

### PR DESCRIPTION
**Pull request by alemorozov**
Closes #108

### CODE REVIEW

**Comment by ronaldtse** [comment]
@alexeymorozov since this webcore package contains different versioned fonts from the previous package, we need to have two separate formulas. Can you help add this as a new formula?

**Comment by ronaldtse** [comment]
The old package could be called `opensuse-webcore-fonts` and the new package can be called `pclinuxos-webcore-fonts`.

**Review by ronaldtse — CHANGES_REQUESTED** [review]
Let's keep both the opensuse package and pclinuxos package.

**Comment by alemorozov** [comment]
Done. There are both packages now.

**Comment by ronaldtse** [comment]
Thanks! What is the behavior when someone installs Cambria? Do they download the latest version (i.e. pclos-webcore-fonts)? If they want Arial then they download opensuse-webcore-fonts?

**Comment by alemorozov** [comment]
Yes, when someone installs:

* `Cambria`, the latest `5.24` version is downloaded from `pclinuxos_webcore_fonts` (the new package)
* `Arial`, the latest `3.06` version is downloaded from `ms_truetype` (`opensuse_webcore_fonts` contains the `3.00` version)
* `Wingdings 2`, `opensuse_webcore_fonts` is downloaded on Windows or Linux (macOS has its add-on formula)

**Pull request merged**
