### PR TITLE
#137 Libertinus formula

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #137

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@ronaldtse I'm not sure if we can consider Libertinus as open license?

**Comment by ronaldtse** [comment]
@CAMOBAP yes, it is published under the OFL:
> All typefaces in the Libertinus Fonts project are released under the terms of the Open Font License, version 1.1. See the license file [OFL.txt](https://github.com/alerque/libertinus/blob/master/OFL.txt) for details.

So it is fully open to use.

**Review by ronaldtse — APPROVED** [review]

**Comment by alerque** [comment]
Is there tooling for updating font formulas (version, checksums, license dates, etc.) or does it all need to be done manually by someone?

**Comment by ronaldtse** [comment]
@alerque the easiest way is to use the `fontist create-formula` command:

* https://github.com/fontist/fontist#create-fontist-formulas

This command allows you to create a Formula YAML by having Fontist scan a local or remote (extractable) archive.

You may wish to supplement additional information afterwards manually.

**Comment by ronaldtse** [comment]
I noticed that Libertinus has just had a new release, so the command would be like:

```sh
$ fontist create-formula https://github.com/alerque/libertinus/releases/download/v7.051/Libertinus-7.051.zip
```

The command will automatically obtain metadata from the TTF/OTF files to fill in the formula.

@alerque Thanks for checking on Fontist for Libertinus! 👍

**Pull request merged**
