### PR TITLE
Use TTF files for URW-Base35-Fonts

### LINKED ISSUE #163: Set font file D050000L.ttf
Source issue: https://github.com/metanorma/pdfa-iso-32000-2/issues/11#issuecomment-1811466267

Currently, the font file `D050000L.otf` is using for the font `D050000L`:
https://github.com/fontist/formulas/blob/8d759905824627c5d2b34efc57932e04c0a42814/Formulas/urw-base35-fonts.yml#L49

We need to change it to TTF version: `D050000L.ttf`.

### PR DESCRIPTION
**Pull request by alemorozov**
Closes #163

### CODE REVIEW

**Comment by alemorozov** [comment]
Changed the files but now metanorma started to fail:

https://github.com/metanorma/metanorma/actions

https://github.com/metanorma/metanorma/actions/runs/6930602944 - here

**Comment by ronaldtse** [comment]
Can we only use TTF for the D050000L font but OTF for the rest?

**Comment by ronaldtse** [comment]
@alexeymorozov looks like the failures are not related to the font?

**Comment by alemorozov** [comment]
Yes, I see they are already being handled in several metanorma PRs.

**Comment by ronaldtse** [comment]
Thank you @alexeymorozov !

**Pull request merged**
